routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return redirect()->route('login');
});
// Route::get('/admin/dashboard', 'Admin\DashboardController@index')->middleware('auth', 'admin');

Route::prefix('admin')->middleware(['auth', 'admin'])
->group(function(){
    // pengembang
    Route::resource('kel-pengembang', 'Manag\ManagPengembangController');
    Route::resource('kel-mentor', 'Manag\KelMentorController');
    Route::resource('kel-kememberan', 'Manag\KememberanController');

    // kelas
    Route::resource('kelas', 'Admin\KelasController');

    // hadiah
    Route::get('hadiah', 'Manag\HadiahController@index')->name('index-hadiah');
    Route::get('hadiah/create', 'Manag\HadiahController@create')->name('create-hadiah');
    Route::post('hadiah/store', 'Manag\HadiahController@store')->name('hadiah-store');
    Route::get('hadiah/edit/{id}', 'Manag\HadiahController@edit')->name('edit-hadiah');
    Route::put('hadiah/update/{id}', 'Manag\HadiahController@update')->name('update-hadiah');
    Route::get('hadiah/delete/{id}', 'Manag\HadiahController@delete')->name('delete-hadiah');
    Route::get('hadiah/update/status/{id}', 'Manag\HadiahController@hendleSuksessHadiah')->name('hendle-hadiah-sukses');

    Route::get('dashboard', 'Manag\PendapatanKelasController@index')->name('dashboard'); //di controller pendapatan
    Route::get('kel-transaksi', 'Manag\ManagTransaksiController@index')->name('kel-transaksi');

    // BERLANGGANAN
    Route::resource('kel-berlangganan', 'Manag\ManagBerlanggananController');

    // transaksi manual
    Route::get('transaksi', 'Manag\ManagTransaksiManualController@index')->name('home-transaksi-manual');
    Route::get('set-transaksi/{id}', 'Manag\ManagTransaksiManualController@setSuksess')->name('set-sukses-transaksi');
    Route::get('set-transaksi-gagal/{id}', 'Manag\ManagTransaksiManualController@setFailed')->name('set-gagal-transaksi');

});

Route::prefix('pengembang')->middleware(['auth'])->group(function(){
    Route::resource('pengajar', 'Admin\MentorController');
    // Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    // Route::resource('kelas', 'Admin\KelasController');
    // materi
    // chapter
    Route::post('kelas/bab/create', 'Admin\MateriController@tambahBAB')->name('chapter-create');
    Route::get('kelas/bab/hapus/{id}', 'Admin\MateriController@hapusBAB')->name('chapter-hapus');
    Route::get('kelas/bab/edit/{id}', 'Admin\MateriController@editBAB')->name('chapter-edit');
    Route::put('kelas/bab/update/{id}', 'Admin\MateriController@updateBAB')->name('chapter-update');
    // lesson
    Route::get('kelas/materi/{id}', 'Admin\MateriController@getMateri')->name('materi');
    Route::get('kelas/edit/{course_id}/{id}', 'Admin\MateriController@editLesson')->name('edit-lesson');
    Route::put('kelas/update/{course_id}/{id}', 'Admin\MateriController@updateLesson')->name('update-lesson');
    Route::post('kelas/lesson/create/{id}', 'Admin\MateriController@createLesson')->name('create-lesson');
    Route::get('kelas/lesson/delete/{id}', 'Admin\MateriController@hapusLesson')->name('hapus-lesson');
});
// Route::resource('dasho', 'Admin\MentorController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/keluar', '\App\Http\Controllers\Auth\LoginController@logout')->name('keluar');

app/Http/Controllers/Admin/KelasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Course;
use App\Http\Controllers\Controller;
use App\Kategori;
use App\Mentor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Session;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mentor = Mentor::where('user_id', Auth::user()->id)->with('course')->paginate(10);
        // $mentor = Mentor::where('user_id', Auth::user()->id)->with('course')->get()->pluck('nama', 'id');
        // $tes =[];
        // foreach($mentor as $m)
        // {
        //     dd($m->course);
        // }
        // dd($mentor);
        $allkelas = Course::with('kategori')->paginate(10);

        return view('pages.kelas.index', [
            'items' => $mentor,
            'all_kelas' => $allkelas
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Mentor::where('user_id', Auth::user()->id)->get();
        $mentorAll = Mentor::get();
        $kategori = Kategori::get();

        return view('pages.kelas.create', [
            'items' => $data,
            'kategori' => $kategori,
            'mentor_all' => $mentorAll
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            // 'mentor_id', 'kategori_id', 'nama', 'image', 'sertifikat', 'harga',
        // 'level', 'deskripsi', 'sub_kategori
            'mentor_id' => 'required|integer',
            'nama' => 'string|required',
            'image' => 'image|required',
            'harga' => 'integer|required',
            'level' => 'string',
            'deskripsi' => 'required|string',
            'kategori_id' => 'required|integer',
            'sub_kategori' => 'required|string'

        ]);
        $data = $request->all();
        $image = $request->file('image')->store('assets/kelas', 'public');
        $data['image'] = url('storage/'.$image);
        $data['sertifikat'] = 1;
        // dd($data);
        $course = Course::create($data);

        return redirect()->route('kelas.index')->with('toast_success', 'kelas berhasil di tambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Course::findOrFail($id);
        // dd($data);
        $mentor = Mentor::where('user_id', Auth::user()->id)->get();
        $mentorAll = Mentor::get();
        $kategori = Kategori::get();

        return view('pages.kelas.edit', [
            'kelas' => $data,
            'mentor' => $mentor,
            'kategori' => $kategori,
            'mentor_all' => $mentorAll
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $course = Course::findOrFail($id);
        // dd($data);
        if($request->file('image'))
        {
            $image = $request->file('image')->store('assets/kelas', 'public');
            $data['image'] = url('storage/'.$image);
        }

        // dd($data);

        $course->update($data);
        return Redirect::route('kelas.index')->with('success', 'Kelas Berhasil di Update.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Course::findOrFail($id);

        if(!$data)
        {
            return Redirect::back()->with('error', 'Gagal Hapus Kelas.');
        }

        $data->delete();
        return Redirect::back()->with('toast_success', 'Kelas Berhasil di Hapus.');
    }
}

resources/views/pages/kelas/create.blade.php
@extends('layouts.new-admin')

@section('title')
    Tambah Kelas
@endsection
@section('halaman')
    Tambah Kelas
@endsection

@section('content')
@if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    <div id="app">
            <form action="{{ route('kelas.store') }}" method="post" enctype="multipart/form-data">
            @csrf
                <div class="card p-4">
                    <div class="row">
                        <div class="col-md-3">
                            <img :src="gambar" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="exampleFormControlFile1">Masukan Gambar</label>
                                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image" @change="changeFile">
                            </div>
                        </div>
                        @if (Auth::user()->role === 'pengembang')
                            <div class="col-md-6">
                                <label for="">Pilih Mentor</label>
                                <select class="form-control" name="mentor_id">
                                    @foreach ($items as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                            </div>
                        @endif
                        @if (Auth::user()->role === 'admin')
                            <div class="col-md-6">
                                <label for="">Pilih Mentor</label>
                                <select class="form-control" name="mentor_id">
                                    @foreach ($mentor_all as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                            </div>
                        @endif
                        <div class="col-md-3">
                            <label for="">Pilih Kategori Utama</label>
                            <select class="form-control" name="kategori_id" v-model="pick" @change="onChange($event)">
                                {{-- @foreach ($kategori as $item)
                                    <option>{{ $item->nama }}</option>
                                @endforeach --}}
                                 <option v-for="s in selected" :value="s.id">@{{ s.nama }}</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label for="">Pilih Sub Kategori</label>
                            <select class="form-control" name="sub_kategori" v-if="kategori">
                                <option  v-for="k in kategori" :value="k.nama">@{{ k.nama }}</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="">Judul Kelas</label>
                            <input type="text" class="form-control" placeholder="Masukan judul kelas ..." name="nama" value="{{ old('nama') }}">
                        </div>
                        <div class="col-md-6">
                            <label for="">Price Kelas</label>
                            <input type="number" class="form-control" placeholder="Masukan harga kelas ..." name="harga" value="{{ old('harga') }}">
                        </div>
                        <div class="col-md-12">
                            <label for="">Deskripsi</label>
                            <textarea name="deskripsi" id="" cols="30" rows="10" class="form-control">{{ old('deskripsi') }}</textarea>
                        </div>
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary my-3 btn-block">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
    </div>
@endsection


@push('script')
    <script src="//cdn.ckeditor.com/4.16.0/basic/ckeditor.js"></script>
   <script src="{{ url('backend/vendor/vue/vue.js') }}"></script>
    <script>

        var vm = new Vue({
            el : "#app",
            data : {
                selected: [
                    @foreach($kategori as $k)
                        {
                            id: {{ $k->id }},
                            nama: "{{ $k->nama }}",
                        },
                    @endforeach
                ],
                pick: null,
                kategori : null,
                formal : [
                    {
                        id: 1,
                        nama: 'Sekolah Dasar 1'
                    },
                    {
                        id: 2,
                        nama: 'Sekolah Dasar 2'
                    },
                    {
                        id: 3,
                        nama: 'Sekolah Dasar 3'
                    },
                    {
                        id: 4,
                        nama: 'Sekolah Dasar 4'
                    },
                    {
                        id: 5,
                        nama: 'Sekolah Dasar 5'
                    },
                    {
                        id: 6,
                        nama: 'Sekolah Dasar 6'
                    },
                    {
                        id: 7,
                        nama: 'SMP 1'
                    },
                    {
                        id: 8,
                        nama: 'SMP 2'
                    },
                    {
                        id: 9,
                        nama: 'SMP 3'
                    },
                    {
                        id: 10,
                        nama: 'SMA 1'
                    },
                    {
                        id: 11,
                        nama: 'SMA 2'
                    },
                    {
                        id: 12,
                        nama: 'SMA 3'
                    },

                ],
                informal : [
                    {
                        id: 1,
                        nama : 'Petani',
                    },
                    {
                        id: 2,
                        nama : 'Peternak',
                    },
                    {
                        id: 3,
                        nama : 'Tukang',
                    },
                    {
                        id: 4,
                        nama: 'Buruh',
                    },
                    {
                        id: 5,
                        nama: 'Pengajar',
                    },
                ],
                softskill : [
                    {
                        id: 1,
                        nama: "Komunikasi"
                    },
                    {
                        id: 2,
                        nama: "Kepemimpinan"
                    },
                    {
                        id: 3,
                        nama: "Keuangan"
                    },
                    {
                        id: 4,
                        nama: "Kolaborasi"
                    },
                ],
                hardskill : [
                    {
                        id: 1,
                        nama: "Teknologi"
                    },
                    {
                        id: 2,
                        nama: "Analisa Data"
                    },
                    {
                        id: 3,
                        nama: "Marketing"
                    },
                    {
                        id: 4,
                        nama: "Sales"
                    },
                ],
                gambar : '',

            },
            mounted(){
                console.log(this.gambar);
            },
             methods: {
                changeFile(event) {
                const file = event.target.files[0]
                this.gambar = URL.createObjectURL(file)
                },
                onChange(event) {
                    console.log(event.target.value);
                    // this.kategori = this.formal;
                    if(this.pick === 1){
                        this.kategori = this.formal;
                    }
                    if(this.pick === 2){
                        this.kategori = this.informal;
                    }
                    if(this.pick === 3){
                        this.kategori = this.softskill;
                    }
                    if(this.pick === 4){
                        this.kategori = this.hardskill;
                    }

                    // console.log(this.pick);
                },
                 changeItem: function changeItem(rowId, event) {
                    this.selected = "rowId: " + rowId + ", target.value: " + event.target.value;
                    }
            }
        });
         CKEDITOR.replace( 'deskripsi' );
    </script>
@endpush

resources/views/pages/kelas/edit.blade.php
@extends('layouts.new-admin')

@section('title')
    Edit Kelas
@endsection
@section('halaman')
    Edit Kelas
@endsection

@section('content')
@if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    <div id="app">
            <form action="{{ route('kelas.update', $kelas->id) }}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
                <div class="card p-4">
                    <div class="row">
                        <div class="col-md-3">
                            <img :src="gambar" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="exampleFormControlFile1">Masukan Gambar</label>
                                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image" @change="changeFile">
                            </div>
                        </div>
                        @if (Auth::user()->role === 'pengembang')
                            <div class="col-md-6">
                                <label for="">Pilih Mentor</label>
                                <select class="form-control" name="mentor_id">
                                    @foreach ($mentor as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                            </div>
                        @endif
                        @if (Auth::user()->role === 'admin')
                            <div class="col-md-6">
                                <label for="">Pilih Mentor</label>
                                <select class="form-control" name="mentor_id">
                                    @foreach ($mentor_all as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                            </div>
                        @endif
                        <div class="col-md-3">
                            <label for="">Pilih Kategori Utama</label>
                            <select class="form-control" name="kategori_id" v-model="pick" @change="onChange($event)">
                                {{-- @foreach ($kategori as $item)
                                    <option>{{ $item->nama }}</option>
                                @endforeach --}}
                                 <option v-for="s in selected" :value="s.id">@{{ s.nama }}</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label for="">Pilih Sub Kategori</label>
                            <select class="form-control" name="sub_kategori" v-if="kategori">
                                <option  v-for="k in kategori" :value="k.nama">@{{ k.nama }}</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="">Judul Kelas</label>
                            <input type="text" class="form-control" placeholder="Masukan judul kelas ..." name="nama" value="{{ $kelas->nama }}">
                        </div>
                        <div class="col-md-6">
                            <label for="">Price Kelas</label>
                            <input type="number" class="form-control" placeholder="Masukan harga kelas ..." name="harga" value="{{ $kelas->harga  }}">
                        </div>
                        <div class="col-md-12">
                            <label for="">Deskripsi</label>
                            <textarea name="deskripsi" id="" cols="30" rows="10" class="form-control">{{  $kelas->deskripsi  }}</textarea>
                        </div>
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary my-3 btn-block">Simpan Perubahan</button>
                        </div>
                    </div>
                </div>
            </form>
    </div>
@endsection


@push('script')
    <script src="//cdn.ckeditor.com/4.16.0/basic/ckeditor.js"></script>
   <script src="{{ url('backend/vendor/vue/vue.js') }}"></script>
    <script>

        var vm = new Vue({
            el : "#app",
            data : {
                selected: [
                    @foreach($kategori as $k)
                        {
                            id: {{ $k->id }},
                            nama: "{{ $k->nama }}",
                        },
                    @endforeach
                ],
                pick: null,
                kategori : null,
                formal : [
                    {
                        id: 1,
                        nama: 'Sekolah Dasar 1'
                    },
                    {
                        id: 2,
                        nama: 'Sekolah Dasar 2'
                    },
                    {
                        id: 3,
                        nama: 'Sekolah Dasar 3'
                    },
                    {
                        id: 4,
                        nama: 'Sekolah Dasar 4'
                    },
                    {
                        id: 5,
                        nama: 'Sekolah Dasar 5'
                    },
                    {
                        id: 6,
                        nama: 'Sekolah Dasar 6'
                    },
                    {
                        id: 7,
                        nama: 'SMP 1'
                    },
                    {
                        id: 8,
                        nama: 'SMP 2'
                    },
                    {
                        id: 9,
                        nama: 'SMP 3'
                    },
                    {
                        id: 10,
                        nama: 'SMA 1'
                    },
                    {
                        id: 11,
                        nama: 'SMA 2'
                    },
                    {
                        id: 12,
                        nama: 'SMA 3'
                    },

                ],
                informal : [
                    {
                        id: 1,
                        nama : 'Petani',
                    },
                    {
                        id: 2,
                        nama : 'Peternak',
                    },
                    {
                        id: 3,
                        nama : 'Tukang',
                    },
                    {
                        id: 4,
                        nama: 'Buruh',
                    },
                    {
                        id: 5,
                        nama: 'Pengajar',
                    },
                ],
                softskill : [
                    {
                        id: 1,
                        nama: "Komunikasi"
                    },
                    {
                        id: 2,
                        nama: "Kepemimpinan"
                    },
                    {
                        id: 3,
                        nama: "Keuangan"
                    },
                    {
                        id: 4,
                        nama: "Kolaborasi"
                    },
                ],
                hardskill : [
                    {
                        id: 1,
                        nama: "Teknologi"
                    },
                    {
                        id: 2,
                        nama: "Analisa Data"
                    },
                    {
                        id: 3,
                        nama: "Marketing"
                    },
                    {
                        id: 4,
                        nama: "Sales"
                    },
                ],
                gambar : '{{ $kelas->image }}',

            },
            mounted(){
                console.log(this.gambar);
            },
             methods: {
                changeFile(event) {
                const file = event.target.files[0]
                this.gambar = URL.createObjectURL(file)
                },
                onChange(event) {
                    console.log(event.target.value);
                    // this.kategori = this.formal;
                    if(this.pick === 1){
                        this.kategori = this.formal;
                    }
                    if(this.pick === 2){
                        this.kategori = this.informal;
                    }
                    if(this.pick === 3){
                        this.kategori = this.softskill;
                    }
                    if(this.pick === 5){
                        this.kategori = this.hardskill;
                    }

                    // console.log(this.pick);
                },
                 changeItem: function changeItem(rowId, event) {
                    this.selected = "rowId: " + rowId + ", target.value: " + event.target.value;
                    }
            }
        });
         CKEDITOR.replace( 'deskripsi' );
    </script>
@endpush