routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return redirect()->route('login');
});
// Route::get('/admin/dashboard', 'Admin\DashboardController@index')->middleware('auth', 'admin');

Route::prefix('admin')->middleware(['auth', 'admin'])
->group(function(){
    // pengembang
    Route::resource('kel-pengembang', 'Manag\ManagPengembangController');
    Route::resource('kel-mentor', 'Manag\KelMentorController');
    Route::resource('kel-kememberan', 'Manag\KememberanController');

    // kelas
    Route::resource('kelas', 'Admin\KelasController');

    // hadiah
    Route::get('hadiah', 'Manag\HadiahController@index')->name('index-hadiah');
    Route::get('hadiah/create', 'Manag\HadiahController@create')->name('create-hadiah');
    Route::post('hadiah/store', 'Manag\HadiahController@store')->name('hadiah-store');
    Route::get('hadiah/edit/{id}', 'Manag\HadiahController@edit')->name('edit-hadiah');
    Route::put('hadiah/update/{id}', 'Manag\HadiahController@update')->name('update-hadiah');
    Route::get('hadiah/delete/{id}', 'Manag\HadiahController@delete')->name('delete-hadiah');
    Route::get('hadiah/update/status/{id}', 'Manag\HadiahController@hendleSuksessHadiah')->name('hendle-hadiah-sukses');

    Route::get('dashboard', 'Manag\PendapatanKelasController@index')->name('dashboard'); //di controller pendapatan
    Route::get('kel-transaksi', 'Manag\ManagTransaksiController@index')->name('kel-transaksi');

    // BERLANGGANAN
    Route::resource('kel-berlangganan', 'Manag\ManagBerlanggananController');

    // transaksi manual
    Route::get('transaksi', 'Manag\ManagTransaksiManualController@index')->name('home-transaksi-manual');
    Route::get('set-transaksi/{id}', 'Manag\ManagTransaksiManualController@setSuksess')->name('set-sukses-transaksi');
    Route::get('set-transaksi-gagal/{id}', 'Manag\ManagTransaksiManualController@setFailed')->name('set-gagal-transaksi');

});

Route::prefix('pengembang')->middleware(['auth'])->group(function(){
    Route::resource('pengajar', 'Admin\MentorController');
    // Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    // Route::resource('kelas', 'Admin\KelasController');
    // materi
    // chapter
    Route::post('kelas/bab/create', 'Admin\MateriController@tambahBAB')->name('chapter-create');
    Route::get('kelas/bab/hapus/{id}', 'Admin\MateriController@hapusBAB')->name('chapter-hapus');
    Route::get('kelas/bab/edit/{id}', 'Admin\MateriController@editBAB')->name('chapter-edit');
    Route::put('kelas/bab/update/{id}', 'Admin\MateriController@updateBAB')->name('chapter-update');
    // lesson
    Route::get('kelas/materi/{id}', 'Admin\MateriController@getMateri')->name('materi');
    Route::get('kelas/edit/{course_id}/{id}', 'Admin\MateriController@editLesson')->name('edit-lesson');
    Route::put('kelas/update/{course_id}/{id}', 'Admin\MateriController@updateLesson')->name('update-lesson');
    Route::post('kelas/lesson/create/{id}', 'Admin\MateriController@createLesson')->name('create-lesson');
    Route::get('kelas/lesson/delete/{id}', 'Admin\MateriController@hapusLesson')->name('hapus-lesson');
});
// Route::resource('dasho', 'Admin\MentorController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/keluar', '\App\Http\Controllers\Auth\LoginController@logout')->name('keluar');

app/Mentor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mentor extends Model
{
    protected $fillable = [
        'nama', 'email', 'profesi', 'image', 'no_rekening', 'user_id'
    ];

    public function course()
    {
        return $this->hasMany('App\Course');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/MentorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Course;
use App\Http\Controllers\Controller;
use App\Mentor;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MentorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = Mentor::with('course')->get();
        $data = Mentor::where('user_id', Auth::user()->id)->withCount('course')->get();
        // dd($data);
        // $m =    Mentor::collection();
        // $data = Mentor::where('user_id', Auth::user()->id)->withCount('course')->get();
        // $mycourse = Course::all();
        // foreach($data as $c){
        //     $mycourse = $c->course;
        // }
        // foreach($data as $c){
        //     foreach($c->course as $s){
        //         $mycourse = $s->myCourse;
        //     }
        // }
        // dd($data);


        return view('pages.mentor.index', [
            'items' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Mentor::findOrFail($id);
        // dd($data);
        $user = User::where('role', 'pengembang')->get();

        return view('pages.mentor.edit', [
            'item' => $data,
            'users' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $mentor = Mentor::findOrFail($id);
        // dd($data);
        if($request->file('image'))
        {
            $image = $request->file('image')->store('assets/gallery', 'public');
            $data['image'] = url('storage/'.$image);
        }

        // dd($data);
        $mentor->update($data);
        if(Auth::user()->role === 'admin')
        {
            return redirect()->route('kel-mentor.index')->with('success', 'data mentor berhasil di update');
        }
        return redirect()->route('pengajar.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/MentorController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Mentor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class MentorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Mentor::with('course')->get();

        return response()->json([
            'status' => 'succes',
            'message' => 'data list mentor',
            'data' => $data
        ], 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'nama' => 'string|required',
            'email' => 'string|email|required|unique:mentors',
            'profesi' => 'string|required',
            'image' => 'url|required',
            'no_rekening' => 'required|numeric|min:1'
        ];
        $data = $request->all();
        $validator = Validator::make($data, $rules);
        if($validator->fails()){
            return response()->json([
                'status' => 'error',
                'message' => $validator->errors(),
            ], 400);
        }
        // $image = $request->file('image')->store(
        //     'assets/mentor', 'public');
        //     // dd($data);
        // $data['image'] = url('storage/'.$image);
        // dd($data);
        $mentor = Mentor::create($data);
        return response()->json([
            'status' => 'success',
            'message' => 'data mentor berhasil di tambahkan',
            'data' => $mentor
        ], 200);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Mentor::with('course')->find($id);
        if(!$data)
        {
            return response()->json([
                'status' => 'error',
                'message' => 'data mentor id tidak ada'

            ], 404);
        }

        return response()->json([
            'status' => 'success',
            'message' => 'detail mentor',
            'data' => $data
        ], 200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'nama' => 'string',
            'email' => 'string|email|unique:mentors',
            'profesi' => 'string',
            'image' => 'url'
        ];
        $data = $request->all();
        $validator = Validator::make($data, $rules);
        if($validator->fails()){
            return response()->json([
                'status' => 'error',
                'message' => $validator->errors(),
            ], 400);
        }
        if($request->file('image'))
        {
           $image = $request->file('image')->store(
            'assets/mentor', 'public');
            $data['image'] = url('storage/'.$image);
        }
        $mentor = Mentor::find($id);
        if(!$mentor)
        {
            return response()->json([
                'status' => 'error',
                'message' => 'id mentor tidak ada'
            ], 404);
        }

        $mentor->fill($data);
        $mentor->save();

        return response()->json([
            'status' => 'success',
            'message' => 'data berhasil di update',
            'data' => $mentor
        ], 200);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Mentor::find($id);
        if(!$data)
        {
            return response()->json([
                'status' => 'success',
                'message' => 'data mentor id tidak ada'
            ], 404);
        }

        $data->delete();
        return response()->json([
            'status' => 'success',
            'message' => 'data berhasil di hapus'
        ], 200);
    }


}

resources/views/pages/mentor/edit.blade.php
@extends('layouts.new-admin')

@section('title')
    Edit Mentor
@endsection
@section('halaman')
    Edit Mentor
@endsection

@section('content')
    <div class="card shadow p-4">
        <form action="{{ route('kel-mentor.update', $item->id) }}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <div id="app">
                    <div class="row text-center justify-content-center mb-3">
                        <div class="col-md-3">
                            <img :src="gambar" alt="" class="img-fluid rounded-circle img-mentor">
                            <div class="form-group">
                                <label for="exampleFormControlFile1">Ganti gambar</label>
                                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image" @change="changeFile">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label for="">Nama</label>
                        <input type="text" class="form-control" value="{{ $item->nama }}" name="nama">
                    </div>
                    <div class="col-md-4">
                        <label for="">Email</label>
                        <input type="email" class="form-control" value="{{ $item->email }}" name="email">
                    </div>
                    <div class="col-md-4">
                        <label for="">Profession</label>
                        <input type="text" class="form-control" value="{{ $item->profesi }}" name="profesi">
                    </div>
                    @if (Auth::user()->role === 'admin')
                        <div class="col-md-4">
                            <label for="">Pengembang</label>
                            <select name="user_id" class="form-control">
                                <option value="{{ $item->user->id }}">{{ $item->user->name }}</option>
                                @foreach ($users as $user)
                                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    @endif
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

@push('style')
    <style>
        .rounded-circle{
            width: 150px;
            height: 150px;
            object-fit: cover;
        }
    </style>
@endpush

@push('script')
   <script src="{{ url('backend/vendor/vue/vue.js') }}"></script>
    <script>

        var vm = new Vue({
            el : "#app",
            data : {
                gambar: '{{ $item->image }}',
            },
            mounted(){
                console.log(this.gambar);
            },
             methods: {
                changeFile(event) {
                const file = event.target.files[0]
                this.gambar = URL.createObjectURL(file)
                }
            }
        });
    </script>
@endpush

resources/views/pages/mentor/index.blade.php
@extends('layouts.admin')
@section('title')
    Mentor Page
@endsection
@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Mentor Page Index</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Jumlah Data Tables Mentor </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="text-center">
                            <th>Nama</th>
                            <th>Profession</th>
                            <th>Total Kelas</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($items as $mentor)
                            <tr>
                                <td>{{ $mentor->nama }}</td>
                                <td>{{ $mentor->profesi }}</td>
                                <td>{{ \App\Course::where('mentor_id', $mentor->id)->count() }}</td>
                                <td class="text-center">
                                    <a href="{{ route('kel-mentor.edit', $mentor->id) }}" class="btn btn-info btn-sm mr-1">Edit</a>
                                    {{-- <form action="{{ route('pengajar.destroy', $mentor->id) }}" method="post" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-outline-danger btn-sm">
                                            Hapus
                                        </button>
                                    </form> --}}
                                </td>
                            </tr>
                        @empty
                            Anda Belum Mendaptarkan Mentor. Daftarkan Mentor dan Ambil Peluan Untuk Mendapatkan Penghasilan Lebih
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection