routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return redirect()->route('login');
});
// Route::get('/admin/dashboard', 'Admin\DashboardController@index')->middleware('auth', 'admin');

Route::prefix('admin')->middleware(['auth', 'admin'])
->group(function(){
    // pengembang
    Route::resource('kel-pengembang', 'Manag\ManagPengembangController');
    Route::resource('kel-mentor', 'Manag\KelMentorController');
    Route::resource('kel-kememberan', 'Manag\KememberanController');

    // kelas
    Route::resource('kelas', 'Admin\KelasController');

    // hadiah
    Route::get('hadiah', 'Manag\HadiahController@index')->name('index-hadiah');
    Route::get('hadiah/create', 'Manag\HadiahController@create')->name('create-hadiah');
    Route::post('hadiah/store', 'Manag\HadiahController@store')->name('hadiah-store');
    Route::get('hadiah/edit/{id}', 'Manag\HadiahController@edit')->name('edit-hadiah');
    Route::put('hadiah/update/{id}', 'Manag\HadiahController@update')->name('update-hadiah');
    Route::get('hadiah/delete/{id}', 'Manag\HadiahController@delete')->name('delete-hadiah');
    Route::get('hadiah/update/status/{id}', 'Manag\HadiahController@hendleSuksessHadiah')->name('hendle-hadiah-sukses');

    Route::get('dashboard', 'Manag\PendapatanKelasController@index')->name('dashboard'); //di controller pendapatan
    Route::get('kel-transaksi', 'Manag\ManagTransaksiController@index')->name('kel-transaksi');

    // BERLANGGANAN
    Route::resource('kel-berlangganan', 'Manag\ManagBerlanggananController');

    // transaksi manual
    Route::get('transaksi', 'Manag\ManagTransaksiManualController@index')->name('home-transaksi-manual');
    Route::get('set-transaksi/{id}', 'Manag\ManagTransaksiManualController@setSuksess')->name('set-sukses-transaksi');
    Route::get('set-transaksi-gagal/{id}', 'Manag\ManagTransaksiManualController@setFailed')->name('set-gagal-transaksi');

});

Route::prefix('pengembang')->middleware(['auth'])->group(function(){
    Route::resource('pengajar', 'Admin\MentorController');
    // Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    // Route::resource('kelas', 'Admin\KelasController');
    // materi
    // chapter
    Route::post('kelas/bab/create', 'Admin\MateriController@tambahBAB')->name('chapter-create');
    Route::get('kelas/bab/hapus/{id}', 'Admin\MateriController@hapusBAB')->name('chapter-hapus');
    Route::get('kelas/bab/edit/{id}', 'Admin\MateriController@editBAB')->name('chapter-edit');
    Route::put('kelas/bab/update/{id}', 'Admin\MateriController@updateBAB')->name('chapter-update');
    // lesson
    Route::get('kelas/materi/{id}', 'Admin\MateriController@getMateri')->name('materi');
    Route::get('kelas/edit/{course_id}/{id}', 'Admin\MateriController@editLesson')->name('edit-lesson');
    Route::put('kelas/update/{course_id}/{id}', 'Admin\MateriController@updateLesson')->name('update-lesson');
    Route::post('kelas/lesson/create/{id}', 'Admin\MateriController@createLesson')->name('create-lesson');
    Route::get('kelas/lesson/delete/{id}', 'Admin\MateriController@hapusLesson')->name('hapus-lesson');
});
// Route::resource('dasho', 'Admin\MentorController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/keluar', '\App\Http\Controllers\Auth\LoginController@logout')->name('keluar');

app/Http/Controllers/Manag/HadiahController.php
<?php

namespace App\Http\Controllers\Manag;

use App\Hadiah;
use App\Http\Controllers\Controller;
use App\TukarHadiah;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;

class HadiahController extends Controller
{
    public function index()
    {
        $data = Hadiah::paginate(6);
        $total= Hadiah::count();
        $penukaran_hadiah = TukarHadiah::with('user', 'hadiah')->orderBy('status', 'ASC')->paginate(10);
        $penukaran_hadiah_suksess = TukarHadiah::where('status', 'sukses')->count();
        $penukaran_hadiah_pending = TukarHadiah::where('status', 'pending')->count();
        return view('manag.point.index', [
            'items' => $data,
            'total_hadiah' => $total,
            'tukar_hadiah' => $penukaran_hadiah,
            'CpenukaranS' => $penukaran_hadiah_suksess,
            'CpenukaranP' => $penukaran_hadiah_pending,
        ]);

    }



    public function create()
    {
        return view('manag.point.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            // note, jumlah_point, 'image;
            'note' => 'required|string',
            'jumlah_point' => 'required|numeric',
            'image' => 'required'
        ]);

        $data = $request->all();
        $image = $request->file('image')->store(
            'assets/hadiah', 'public');
            // dd($data);
        $data['image'] = url('storage/'.$image);
        // dd($data);
        $hadiah = Hadiah::create($data);

        return redirect()->route('index-hadiah')->with('toast_success', 'data hadiah berhasil di tambahkan');
    }

    public function edit($id)
    {
        $data = Hadiah::findOrFail($id);

        return view('manag.point.edit', [
            'item' => $data
        ]);
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
      $hadiah = Hadiah::findOrFail($id);
      if($request->file('image'))
      {
          $image = $request->file('image')->store(
            'assets/hadiah', 'public');
            // dd($data);
        $data['image'] = url('storage/'.$image);
      }
    //   dd($data);
    $hadiah->fill($data);
    $hadiah->save();

    return redirect()->route('index-hadiah')->with('toast_success', 'data hadiah berhasil di update');
    }

    public function delete($id)
    {
        $data = Hadiah::find($id);

        $data->delete();

        return redirect()->route('index-hadiah')->with('toast_success', 'data hadiah berhasil di hapus');
    }

    public function hendleSuksessHadiah($id)
    {
        $hadiah = TukarHadiah::findOrFail($id);
        $status = 'sukses';

        $hadiah->update([
            'status' => $status
        ]);
        return redirect()->route('index-hadiah')->with('toast_success', 'data hadiah berhasil di update');
    }
}

app/Http/Controllers/Manag/KelMentorController.php
<?php

namespace App\Http\Controllers\Manag;

use App\Http\Controllers\Controller;
use App\Mentor;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class KelMentorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Mentor::with('course.myCourse')->paginate(20);
        // $data = Mentor::with('course')->sum('id');
        // dd($data);
        $jMentor = Mentor::count();


        return view('manag.mentor.index', [
            'items' => $data,
            'jumlah_mentor' => $jMentor
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = User::all();
        // dd($user);
        $pengembang = User::where('role', 'pengembang')->get();
        // dd($pengembang);

        return view('manag.mentor.create', [
            'users' => $user,
            'pengembang' => $pengembang
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            // 'nama', 'email', 'profesi', 'image', 'no_rekening', 'user_id'
            'nama' => 'required|string',
            'email' => 'required|email|unique:mentors',
            'profesi' => 'required|string',
            'image' => 'required',
            'no_rekening' => 'required',
            'user_id' => 'required|integer'
        ]);

        $data = $request->all();
        $image = $request->file('image')->store(
            'assets/mentor', 'public');
            // dd($data);
        $data['image'] = url('storage/'.$image);

        Mentor::create($data);

        return redirect()->route('kel-mentor.index')->with('toast_success', 'Data mentor berhasil di tambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Mentor::with('user')->findOrFail($id);
        // dd($data);
        $user = User::where('role', 'pengembang')->get();

        return view('pages.mentor.edit', [
            'item' => $data,
            'users' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $mentor = Mentor::findOrFail($id);
        // dd($data);
        if($request->file('image'))
        {
            $image = $request->file('image')->store('assets/gallery', 'public');
            $data['image'] = url('storage/'.$image);
        }

        // dd($data);
        $mentor->update($data);
        if(Auth::user()->role === 'admin')
        {
            return redirect()->route('kel-mentor.index')->with('toast_success', 'data mentor berhasil di update');
        }
        return redirect()->route('kel-mentor.index')->with('toast_success', 'transaki di ubah menjadi gagal');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Mentor::findOrFail($id);
        $data->delete();
        return redirect()->back()->with('success', 'Data Mentor Berhasil di Hapus');
    }
}

app/Http/Controllers/Manag/KememberanController.php
<?php

namespace App\Http\Controllers\Manag;

use App\Http\Controllers\Controller;
use App\Kememberan;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class KememberanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Kememberan::paginate(10);

        return view('manag.kemember.index', [
            'items' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manag.kemember.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'akses_kelas' => 'required',
            'get_point' => 'required',
            'harga' => 'required'

        ]);
        $data = $request->all();
        // dd($data);

        $kememberan = Kememberan::create($data);

        return redirect()->route('kel-kememberan.index')->with('toast_success', 'Kememberan Berhasil di Tambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Kememberan::findOrFail($id);

        return view('manag.kemember.edit', [
            'item' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
            'akses_kelas' => 'required',
            'get_point' => 'required',
            'harga' => 'required'

        ]);
        $data = $request->all();

        $kememberan = Kememberan::findOrFail($id);

        $kememberan->fill($data);
        $kememberan->save();

        return redirect()->route('kel-kememberan.index')->with('toast_success', 'Suksess Update Kememberan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Kememberan::findOrFail($id);
        $data->delete();

        return redirect()->route('kel-kememberan.index')->with('toast_success', 'data kememberan berhasil di delete');
    }
}

app/Http/Controllers/Manag/ManagBerlanggananController.php
<?php

namespace App\Http\Controllers\Manag;

use App\Berlangganan;
use App\Http\Controllers\Controller;
use App\TransaksiManual;
use Illuminate\Http\Request;

class ManagBerlanggananController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Manag/ManagTransaksiController.php
<?php

namespace App\Http\Controllers\Manag;

use App\Http\Controllers\Controller;
use App\Order;
use Illuminate\Http\Request;

class ManagTransaksiController extends Controller
{
    public function index()
    {
        $data = Order::with('user', 'kememberan')->get();
        // $data_count_harga = Order::with('kememberan')->where('status', 'success')->get();
        // // dd($data_count_harga);
        // $total = 0;
        // foreach($data_count_harga as $h)
        // {
        //     $t = $h->kememberan->harga;
        //     $total += $t;
        // }
        $total = TransaksiSukses();
        // dd($total);
        // dd($total, $data_count_harga);
        return view('pages.transaksi.index', [
            'items' => $data,
            'total_transaksi_sukses' => $total,
        ]);

    }
}

app/Http/Controllers/Manag/PendapatanKelasController.php
<?php

namespace App\Http\Controllers\Manag;

use App\Berlangganan;
use App\Chapter;
use App\Course;
use App\Http\Controllers\Controller;
use App\Lesson;
use App\Mentor;
use App\User;
use Illuminate\Http\Request;

class PendapatanKelasController extends Controller
{
    public function index()
    {
        $kelas = Course::withCount('myCourse')->with('kategori', 'mentor')->paginate(6);
        // dd($kelas);
        $counK = Course::count();
        $counM = Mentor::count();
        $counC = Chapter::count();
        $countL = Lesson::count();
        $counP = User::where('role', 'pengembang')->count();
        $BayaraMentor = 0;


        foreach($kelas as $k)
        {
            $t = $k->my_course_count;
            $BayaraMentor += $t;
        }

        $BayaraMentor *= 100;
        // $pendapatan *= 1000;
        $pendapatan = TransaksiSukses();
        $sisaUang = $pendapatan - $BayaraMentor;
        // dd('pendapatan = '.$pendapatan, 'bayaran semua mentor = '. $BayaraMentor, 'Total Pendapatan = '.$sisaUang);
        return view('manag.kelas.pendapata', [
            'kelas' => $kelas,
            'bayar_mentor' => $BayaraMentor,
            'pendapatan' => $pendapatan,
            'sisa_uang' => $sisaUang,
            'count_kelas' => $counK,
            'count_pengembang' => $counP,
            'count_mentor' => $counM,
            'count_chapter' => $counC,
            'count_lesson' => $countL
        ]);
    }
}

resources/views/manag/kemember/create.blade.php
@extends('layouts.new-admin')

@section('title')
    Create Kememberan
@endsection
@section('halaman')
    Buat Kememberan Baru
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        <div class="card-body">
            <form action="{{ route('kel-kememberan.store') }}" method="post" enctype="multipart/form-data">
            @csrf
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Nama</label>
                            <input type="text" class="form-control" id=""  placeholder="Masukan Nama" name="nama" value="{{ old('nama') }}">
                            <small id="emailHelp" class="form-text text-muted">Nama Atau Judul Kememberan.</small>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Harga</label>
                            <input type="number" class="form-control" id="" name="harga" value="{{ old('harga') }}">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Bonus Point</label>
                            <input type="number" class="form-control" id="" name="get_point" value="{{ old('get_point') }}">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Akses Kelas</label>
                            <input type="number" class="form-control" id="" name="akses_kelas" value="{{ old('akses_kelas') }}">
                        </div>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/manag/kemember/edit.blade.php
@extends('layouts.new-admin')

@section('title')
    Create Kememberan
@endsection
@section('halaman')
    Edit Kememberan
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        <div class="card-body">
            <form action="{{ route('kel-kememberan.update', $item->id) }}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Nama</label>
                            <input type="text" class="form-control" id=""  placeholder="Masukan Nama" name="nama" value="{{ $item->nama }}">
                            <small id="emailHelp" class="form-text text-muted">Nama Atau Judul Kememberan.</small>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Harga</label>
                            <input type="number" class="form-control" id="" name="harga" value="{{ $item->harga }}">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Bonus Point</label>
                            <input type="number" class="form-control" id="" name="get_point" value="{{ $item->get_point }}">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Akses Kelas</label>
                            <input type="number" class="form-control" id="" name="akses_kelas" value="{{ $item->akses_kelas }}">
                        </div>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/manag/kemember/index.blade.php
@extends('layouts.new-admin')

@section('title')
    Member Page
@endsection
@section('halaman')
    Member Page
@endsection

@section('content')

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-6">
                    <h6 class="m-0 font-weight-bold text-primary">Jumlah Data Tables Kememberan </h6>
                </div>
                <div class="col-6 text-right">
                    <a href="{{ route('kel-kememberan.create') }}" class="btn btn-primary ">Tambah Kememberan</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="text-center">
                            <th>Nama</th>
                            <th>Harga</th>
                            <th>Akses Kelas</th>
                            <th>Bonus Point</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($items as $item)
                            <tr>
                                <td>{{ $item->nama }}</td>
                                <td>{{ $item->harga }}</td>
                                <td>{{ $item->akses_kelas }}</td>
                                <td>{{ $item->get_point }}</td>
                                <td>
                                    <a href="{{ route('kel-kememberan.edit', $item->id) }}" class="btn btn-info btn-sm mr-1">Edit</a>
                                    <form action="{{ route('kel-kememberan.destroy', $item->id) }}" method="post" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-outline-danger btn-sm" onclick="return confirm('Yakin Akan di Hapus?')">
                                            Hapus
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr class="text-center">
                                <td colspan="5"><h5>Data Kememberan Kosong</h5></td>
                            </tr>
                        @endforelse
                        {{ $items->links() }}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection